paths-ignore:
  - 'examples/**/*'

allowlist:
  # Slack Bot Token pattern
  - pattern: 'xoxb-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{30}'
    reason: 'Example Slack bot token in documentation'

  # Slack Team ID pattern
  - pattern: 'T[A-Z0-9]{8}'
    reason: 'Example Slack Team ID in documentation'

  # Slack Channel ID pattern
  - pattern: 'C[A-Z0-9]{8}'
    reason: 'Example Slack Channel ID in documentation'

  # Atlassian API Token pattern
  - pattern: 'ATATT[a-zA-Z0-9]{100,}'
    reason: 'Example Atlassian API token in documentation'

  # GitHub Personal Access Token pattern
  - pattern: 'ghp_[a-zA-Z0-9]{36}'
    reason: 'Example GitHub Personal Access Token in documentation'
